name: Release Spring as Dockerimage

concurrency: release

on:
  push:
    tags:
      - v*

env:
  VERSION: ""
  ARTIFACT_NAME: scoutventure-api

jobs:
  build-spring:
    name: Build Spring App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: Set up JDK 17
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests -Dversion=${{env.VERSION}}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target/*.jar

  build-docker-image:
    name: Build Docker Image and Upload to Registry
    needs: build-spring
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Extract tag name without 'v' prefix and set as env variable
        run: |
          VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: Download Build Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./spring/target

      - name: Login to Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{vars.DOCKER_REGISTRY_URL}}
          username: ${{vars.DOCKER_REGISTRY_USERNAME}}
          password: ${{secrets.DOCKER_REGISTRY_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          push: true
          tags: |
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:latest
            ${{vars.DOCKER_REGISTRY_URL}}/${{env.ARTIFACT_NAME}}:${{env.VERSION}}
          file: ./docker/spring/Dockerfile
